apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app"
  labels:
    app: "app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "app"
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
        - name: "app"
          image: tf2-trade-finder_trade_finder:latest
          #image: python:3.11
          imagePullPolicy: Never
          # ports:
          #   - containerPort: 3306
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef: 
                  name: mysql-config
                  key: mysql-url
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PASS
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql_user                  
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PASS
            # envFrom:
            #   - configMapRef:
            #       name: mysql-config
          # resources:
          #   limits:
          #     memory: 250Mi
          #   requests:
          #     cpu: 200m
          #     memory: 200Mi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: "app-service"
# spec:
#   ports:
#   - port: 3306
#     protocol: TCP
#     #targetPort: 3306
#   selector:
#     app: "app"
  #type: LoadBalancer
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: mysql
# spec:
#   type: ExternalName
#   externalName: localhost
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-sql
subsets:
  - addresses:
      -
        ip: "10.105.253.164"
    ports:
      -
        port: 3306
        name: "mysql-db"