apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-finder
  labels:
    app: trade-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-finder
  template:
    metadata:
      labels:
        app: trade-finder
    spec:
      containers:
      - name: trade-finder
        image: tf2-trade-finder_trade_finder:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef: 
                name: mysql-config
                key: mysql-url
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_PASS
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mysql_user                  
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_PASS